# Generated by Django 4.1.9 on 2023-05-15 22:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="this is the unique identifier of an object",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Modified date when the record was created.",
                        max_length=20,
                        verbose_name="Modified Date",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="product category name",
                        max_length=255,
                        verbose_name="Category name",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="Timestamp when the category was created",
                        verbose_name="Created Date",
                    ),
                ),
            ],
            options={
                "verbose_name": "Base Model",
                "verbose_name_plural": "Base Model",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="this is the unique identifier of an object",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when the record was created.",
                        max_length=20,
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Modified date when the record was created.",
                        max_length=20,
                        verbose_name="Modified Date",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="This holds the name of the product",
                        max_length=255,
                        null=True,
                        verbose_name="Product name",
                    ),
                ),
                (
                    "product_description",
                    models.CharField(
                        blank=True,
                        help_text="This holds the description of the product",
                        max_length=500,
                        null=True,
                        verbose_name="Product description",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        help_text="This holds the price of the product",
                        max_digits=300,
                        null=True,
                        verbose_name="Product price",
                    ),
                ),
                (
                    "product_image",
                    models.ImageField(
                        blank=True,
                        help_text="Product images, which should be in PNG, JPEG, or JPG format",
                        null=True,
                        upload_to="photos/product_image",
                        verbose_name="Product Image",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text=" This is a product category",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Product_category",
                        to="store.category",
                        verbose_name="product category name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Base Model",
                "verbose_name_plural": "Base Model",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="this is the unique identifier of an object",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when the record was created.",
                        max_length=20,
                        verbose_name="Created Date",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Modified date when the record was created.",
                        max_length=20,
                        verbose_name="Modified Date",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Product images, which should be in PNG, JPEG, or JPG format",
                        null=True,
                        upload_to="photos/properties_image",
                        verbose_name="Product Image",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product of which the images belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
                "ordering": ("-created_date",),
            },
        ),
    ]
