# Generated by Django 4.2.1 on 2023-05-17 16:11

import autoslug.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import store.validators


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("store", "0002_colour_colourinventory_couponcode_productimage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="This holds the name of the category",
                max_length=255,
                verbose_name="Category Name",
            ),
        ),
        migrations.AlterField(
            model_name="colour",
            name="name",
            field=models.CharField(
                help_text="This holds the name of the colour",
                max_length=20,
                unique=True,
                verbose_name="Colour Name",
            ),
        ),
        migrations.AlterField(
            model_name="colourinventory",
            name="colour",
            field=models.ForeignKey(
                help_text=" This holds the color of the product",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_color",
                to="store.colour",
                verbose_name="Product Colour",
            ),
        ),
        migrations.AlterField(
            model_name="colourinventory",
            name="extra_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text=" This holds the Extra Price given to the product",
                max_digits=6,
                null=True,
                verbose_name="Extra Price",
            ),
        ),
        migrations.AlterField(
            model_name="colourinventory",
            name="product",
            field=models.ForeignKey(
                help_text=" This holds the product that has the colour",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="color_inventory",
                to="store.product",
                verbose_name="Product Detail",
            ),
        ),
        migrations.AlterField(
            model_name="colourinventory",
            name="quantity",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text=" This holds the quantity of the product",
                verbose_name="Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="couponcode",
            name="code",
            field=models.CharField(
                editable=False,
                help_text=" This holds the Coupon code of the product",
                max_length=8,
                unique=True,
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="couponcode",
            name="expired",
            field=models.BooleanField(
                default=False,
                help_text="This holds the code action if active or not",
                verbose_name="Expired",
            ),
        ),
        migrations.AlterField(
            model_name="couponcode",
            name="expiry_date",
            field=models.DateTimeField(
                help_text=" This holds the expiry date of the code",
                verbose_name="Expiry Date",
            ),
        ),
        migrations.AlterField(
            model_name="couponcode",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text=" This holds the Coupon price of the product",
                max_digits=6,
                verbose_name="Price",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                help_text="This holds the category the product belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="store.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="This holds the description of the product",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="featured_product",
            field=models.BooleanField(
                default=False,
                help_text=" This holds the featured product",
                verbose_name="Featured Product",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="flash_sale_end_date",
            field=models.DateTimeField(
                blank=True,
                help_text=" This holds the flashsale end date of the product",
                null=True,
                verbose_name="Flashsale End Date",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="flash_sale_start_date",
            field=models.DateTimeField(
                blank=True,
                help_text=" This holds the flashsale start date of the product",
                null=True,
                verbose_name="Flashsale Start Date",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="inventory",
            field=models.IntegerField(
                help_text=" This holds the inventory details of the product",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Inventory",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="percentage_off",
            field=models.PositiveIntegerField(
                default=0,
                help_text=" This holds the percentage of the product will be sold off",
                verbose_name="Percentage Off",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="This holds the price or amount of the product",
                max_digits=6,
                verbose_name="Price",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="seller",
            field=models.ForeignKey(
                help_text="This holds the owner or seller of the product (user)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="core.seller",
                verbose_name="Seller",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="shipping_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text=" This holds the shipping fee of the product",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Shipping Fee",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="shipping_out_days",
            field=models.IntegerField(
                default=0,
                help_text=" This holds the shipping days of the product",
                verbose_name="Shipping Out Days",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                editable=False,
                help_text=" This holds the slug of the product",
                null=True,
                populate_from="title",
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="style",
            field=models.CharField(
                help_text="This holds the style of the product",
                max_length=255,
                null=True,
                verbose_name="Style",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(
                help_text="This holds the title of the product",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Title",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="_image",
            field=models.ImageField(
                help_text=" This holds the image of the product",
                upload_to="store/images",
                validators=[store.validators.validate_image_size],
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                help_text=" This holds the Id or details of the product that owns the image",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="store.product",
                verbose_name="Product Details",
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="customer",
            field=models.ForeignKey(
                help_text=" This holds the customer details that owns the review of the product",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="product_reviews",
                to="core.customer",
                verbose_name="Customer",
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="description",
            field=models.TextField(
                help_text=" This holds the descriptions of review the product has",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="product",
            field=models.ForeignKey(
                help_text=" This holds the details of the product on review",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_reviews",
                to="store.product",
                verbose_name="Product Details",
            ),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="ratings",
            field=models.IntegerField(
                choices=[
                    (1, "1 star"),
                    (2, "2 stars"),
                    (3, "3 stars"),
                    (4, "4 stars"),
                    (5, "5 stars"),
                ],
                help_text=" This holds the rating of the product",
                null=True,
                verbose_name="Rating",
            ),
        ),
        migrations.AlterField(
            model_name="productreviewimage",
            name="_image",
            field=models.ImageField(
                help_text=" This holds the image of the product on review",
                upload_to="store/product_reviews",
                validators=[store.validators.validate_image_size],
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="productreviewimage",
            name="product_review",
            field=models.ForeignKey(
                help_text=" This holds the product the image belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_review_images",
                to="store.productreview",
                verbose_name="Product Review Image",
            ),
        ),
        migrations.AlterField(
            model_name="size",
            name="title",
            field=models.CharField(
                help_text="This holds the size of the product",
                max_length=5,
                unique=True,
                verbose_name="Size",
            ),
        ),
        migrations.AlterField(
            model_name="sizeinventory",
            name="extra_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text=" This holds the extra price of the product",
                max_digits=6,
                null=True,
                verbose_name="Extra Price",
            ),
        ),
        migrations.AlterField(
            model_name="sizeinventory",
            name="product",
            field=models.ForeignKey(
                help_text=" This holds the detail of the product",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="size_inventory",
                to="store.product",
                verbose_name="Product Detail",
            ),
        ),
        migrations.AlterField(
            model_name="sizeinventory",
            name="quantity",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text=" This holds the quantity of the product",
                verbose_name="Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="sizeinventory",
            name="size",
            field=models.ForeignKey(
                help_text=" This holds the size of the product",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_size",
                to="store.size",
                verbose_name="Product Size",
            ),
        ),
    ]
