# Generated by Django 4.2.1 on 2023-05-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_address_cart_country_order_alter_colour_hex_code_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"verbose_name_plural": "Cart"},
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="This holds the price or amount of the product",
                max_digits=8,
                verbose_name="Price",
            ),
        ),
    ]
