# Generated by Django 4.2.1 on 2023-05-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customer_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='ratings',
            field=models.IntegerField(null=True),
        ),
    ]
