FIRST_STAR = 1
TWO_STARS = 2
THREE_STARS = 3
FOUR_STARS = 4
FIVE_STARS = 5

RATING_CHOICES = (
    (FIRST_STAR, "1 star"),
    (TWO_STARS, "2 stars"),
    (THREE_STARS, "3 stars"),
    (FOUR_STARS, "4 stars"),
    (FIVE_STARS, "5 stars")
)

PAYMENT_PENDING = "P"
PAYMENT_COMPLETE = "C"
PAYMENT_FAILED = "F"

PAYMENT_STATUS = (
    (PAYMENT_PENDING, "Pending"),
    (PAYMENT_COMPLETE, "Complete"),
    (PAYMENT_FAILED, "Failed"),
)

SHIPPING_STATUS_PENDING = "P"
SHIPPING_STATUS_SHIPPED = "PR"

SHIPPING_STATUS_CHOICES = (
    (SHIPPING_STATUS_PENDING, "Pending"),
    (SHIPPING_STATUS_SHIPPED, "Shipping"),
)