# Generated by Django 4.1.9 on 2023-05-15 22:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="country",
            name="iso2",
        ),
        migrations.RemoveField(
            model_name="country",
            name="native",
        ),
        migrations.RemoveField(
            model_name="country",
            name="phone_code",
        ),
    ]
